# Generated by Django 3.1.7 on 2021-04-05 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('doc', models.DateTimeField(default=datetime.datetime(2021, 4, 5, 9, 38, 39, 199964, tzinfo=utc), verbose_name='date published')),
                ('modify_date', models.DateTimeField(default=datetime.datetime(2021, 4, 5, 9, 38, 39, 199964, tzinfo=utc), verbose_name='date published')),
            ],
        ),
    ]
